name: Análisis de Seguridad

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Instalar Bandit
        run: |
          pip install bandit
      - name: Analizar código con Bandit
        run: |
          bandit -r .